"""empty message

Revision ID: 806a0d8b2792
Revises: 
Create Date: 2024-02-09 12:05:36.399793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806a0d8b2792'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('libro')
    # ### end Alembic commands ###
